### ISSUE TITLE
sf、spu属于全局级的（进程级的），如何处理多任务并发

### ISSUE THREAD

**Issue by hy928302776** [secretflow/secretflow#473]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow/secretflow-anolis8:0.7.18b2

### OS Platform and Distribution

Centos7 4c32g

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
1、比如咱们的隐语平台，我创建不同的项目，每个项目不同的节点进行sf，spu初始化。因为sf和spu是进程级的，所以每次执行任务就必须创建子进程处理数据。但是进程级的创建和取消，太消耗资源。这方便如何处理呢？
2、任务流程异步执行时，每次异步执行也都是要重新sf.init吗？
3、在测试spu计算的时候发现是串型执行的？比如一键压测spu计算，每个任务是串型执行的
那我们该如何管理sf的以上调度问题呢？
```

### Reproduction code to reproduce the issue.

```shell
1、比如咱们的隐语平台，我创建不同的项目，每个项目不同的节点进行sf，spu初始化。因为sf和spu是进程级的，所以每次执行任务就必须创建子进程处理数据。但是进程级的创建和取消，太消耗资源。这方便如何处理呢？
2、任务流程异步执行时，每次异步执行也都是要重新sf.init吗？
3、在测试spu计算的时候发现是串型执行的？比如一键压测spu计算，每个任务是串型执行的，不知道我测试的对不对
那我们该如何管理sf的以上调度问题呢？
```

**Comment by da-niao-dan** [comment]
Secretflow uses ray to handle parallel computing issues. See https://docs.ray.io/en/latest/ray-overview/index.html.

1. We write the program without explicit scheduling: init sf, and spu devices once and do all computations you want.
2. As long as two task do not have dependency issue, they are async. We don't need to do sf.init() each time.
3. Tasks with a line of dependency will be executed in line. 

You may find this [blog](https://towardsdatascience.com/modern-parallel-and-distributed-python-a-quick-tutorial-on-ray-99f8d70369b8) helpful.

Each time when we use SPU or PYU to execute tasks, we will issue the underlying ray tasks to accomplish them. If two tasks are not related, they should be async.

Also note that computations are lazy. Scheduled task may be not actually executed until we really need the results.

Note also that, due to limitation of GIL lock in python, when we need to use multiple CPUs for a single python process, we have to rely on computations outsourced to C++ libraries such as numpy, or HEU/SPU computations to do this cleanly.

**Comment by hy928302776** [comment]
非常感谢，但还是有个疑问：
我们在没有明确调度的情况下编写程序：可以一次初始化 sf 和 spu 设备，然后进行所有你想要的计算。

但是，我们动态添加节点又该如何初始化sf和spu呢？
假如A节点分别需要和B、C等节点进行数据处理，于是同时将A、B、C等放在一起进行一次sf初始化，进行数据计算。
如果这时候又有D和E节点加入，该怎么办？重新将A、B、C、D、E一起sf初始化吗？这个时候，A、B、C如果有正在执行的任务就会受到影响。

**Comment by 6fj** [comment]
@hy928302776 

目前是需要重新初始化的

**Comment by zhouaihui** [comment]
hi, @hy928302776 , 目前SecretFlow是离线任务模式，每个任务的参与方是不支持动态扩缩（需要提前给出所有的参与方）。如果要在运行过程中添加节点，目前只能再起一个新的任务。

方便的话，可以更详细的分享下你描述的需求场景是什么。比如，什么场景情况下需要中途加入新的节点？

**Comment by hy928302776** [comment]
核心企业和多个供应商要实现对账，企业和供应商的合作关系是变化的，中途也会有新的供应商加入（或接入隐私计算），虽然不频繁，但是也有这种情况。

**Comment by 6fj** [comment]
hi @hy928302776 

隐私计算任务的调度和并发会由我们的新开源项目处理，敬请期待。

**Comment by 472002463** [comment]
> As long as two task do not have dependency issue, they are async. We don't need to do sf.init() each time.

@da-niao-dan 
Excuse me, What does this mean, that if a DAG graph comes in and executes according to the topology sort, it will automatically compute in parallel, without having to construct the adjacency list for parallel scheduling?

>隐私计算任务的调度和并发会由我们的新开源项目处理，敬请期待。

@6fj 请问下，这个调度开源的框架，我上面说的关于并行调度的问题吗，那DAG图中的节点算子还需要自己封装吗

**Comment by 6fj** [comment]
是的，调度会有新开源的框架来处理。

节点算子需要自己封装，但是常用算子我们会帮用户封装好

**Comment by 6fj** [comment]
Please check https://github.com/secretflow/kuscia
