### ISSUE TITLE
the method of woe computing is not safe enough

### ISSUE THREAD

**Issue by huajinghua** [secretflow/secretflow#565]
### Issue Type

Bug

### Source

binary

### Secretflow Version

all

### OS Platform and Distribution

max

### Python version

3.8

### What happend and What you expected to happen.

```shell
i think the method of woe computing is not safe enough,it leaks unnecessary info to others
```

### Reproduction code to reproduce the issue.

```shell
the preprocessing script :preprocessing/binning/vert_woe_binning.py 

bins_positive = self.secure_device(spu_work)(
                    secure_label, bin_select.to(self.secure_device)
                ).to(device)
* i think it's not safe enough when you reveal bin_positive info to the device which doesn't hold the label.it will leak postive label count info. 
if a feature has only two bins and has big correlation with label,maybe the adversary can guess the label?
* anyway,this method of computing woe leak unnecessary info in this script.
* i think the best way is to computing woe in whole encrypted until get final result,so the good_rate、bad_rate and ln(good_rate/bad_rate) should be computed in secret sharing mode.how do you think?
```

**Comment by huajinghua** [comment]
and the problem also exists when computing woe in HEU device method?

**Comment by da-niao-dan** [comment]
Hi, this is a great question!
The definition of secure mpc is that we reveal nothing except the final results.
However, in practive, we need to notice that anything can inferred by the final results is also revealed automatically,

In this case, let's consider what the feature holder will know:
1.  WOE and iv for each bin will be revealed (becaue those are final results).
2. In addition, the total count of samples (= total_labels) and the total count of samples for each bin are also known.

From the above information, the bins_positive can be easily inferred.

Note any one bin's woe, iv are known.

_bin_total_ = bin_positives + bin_negatives
_total_labels_ = total_positives + total_negatives
_bin_woe_ = log((bin_positives / total_positives) / (bin_negatives / total_negatives))
_bin_iv_ = ((bin_positives / total_positives) - (bin_negatives / total_negatives)) * _bin_woe_

The italic variables are known. We can surely solve a system of nonlinear equations.

To be more specific, (skip the following part if you know how to solve the above equations) let's calculate bin_positives.

e^{_bin_woe_} = (bin_positives / total_positives) / (bin_negatives / total_negatives)

denote
bp = bin_positives / total_positives
bn = bin_negatives / total_negatives

and from above we have
bp = e^{_bin_woe_} bn

then
_bin_iv_ = (bp - bn) * _bin_woe_  = ( e^{_bin_woe_} - 1) bn *_bin_woe_

hence
bn = _bin_iv_ /( e^{_bin_woe_} - 1)/_bin_woe_
then
bp = _bin_iv_ /( e^{_bin_woe_} - 1)/_bin_woe_ *  e^{_bin_woe_} 

Now we have

_bin_total_ = bin_positives + bin_negatives
_total_labels_ = total_positives + total_negatives
bin_positives / total_positives = _bin_iv_ /( e^{_bin_woe_} - 1)/_bin_woe_ *  e^{_bin_woe_} 
bin_negatives / total_negatives = _bin_iv_ /( e^{_bin_woe_} - 1)/_bin_woe_

so

total_positives = bin_positives / (_bin_iv_ /( e^{_bin_woe_} - 1)/_bin_woe_ *  e^{_bin_woe_} )
(_bin_total_ - bin_positives)/ (_total_labels_ - total_positives) = _bin_iv_ /( e^{_bin_woe_} - 1)/_bin_woe_

By substitute total_positives , we can solve for bin_positives.


We can conclude that from the woe final results, we can infer bin_positives.

Since bin_positives will be known anyways, we can surely reveal it early anyways.

Hence there is no security loss for the current approach. 

Delay revealing bins_positive will cost more unnecessary computations.

And the same applies for HEU device method.

**Comment by huajinghua** [comment]
thanks for your deduction! 
firstly, i think bin_iv can be keep encrypted in the party which doesn't hold label. sometimes we only need iv of the feature,but not iv of bin.
when bin_woe and  feature_iv were cacluated, we can only use bin_woe to transform data.and bin_iv can be ignored.
then,when bin_num>2,i think you can't get bins_positive without bin_iv, may be i am wrong?
lastly,i metion this question is that is another federated learning framework(FATE),they didn't leak positive counts to adversary,and they didn't return bin_iv to the party without label.
whatever,thanks for you answer.

**Comment by da-niao-dan** [comment]
Hi,
You are right! It's a great idea.
We will provide the option to calculate featrure_iv only in later release, and therefore will protect bins_positive in that option!

**Comment by da-niao-dan** [comment]
Thanks again for bringing this issue up. This issue will be resolved in our next release, so I am closing this issue now.
