### ISSUE TITLE
How SecretPad deployed at local machine from MVP package connects with other entities and performs privacy computing?

### ISSUE THREAD

**Issue by LeoneChen** [secretflow/secretflow#857]
How SecretPad deployed at local machine from [MVP ](https://www.secretflow.org.cn/docs/quickstart/mvp-platform) package connects with other remote entities and performs privacy computing?

On the other hand, I found the SecretPad in [Online Experience](https://www.secretflow.org.cn/docs/quickstart/uti941fxkadpuwd3) provide a step to invite other institutions with their UUID. 

I think some people may not trust server deployed online by SecretFlow.

**Comment by 6fj** [comment]
Hi @LeoneChen 

MVP version of SecretPad is only for demo. Main purpose is to simulate procedures which the production(including on-premise and cloud) version have. So you can't use MVP version of SecretPad to connect to other entities at all.

**Comment by LeoneChen** [comment]
Nice to see again~

Any method to prove SecretPad run in online is in consist with the code public at [secretpad-frontend](https://github.com/secretflow/secretpad-frontend) and [secretpad](https://github.com/secretflow/secretpad-frontend).

Since once a company want to prove their production can be trust, it's a common need in some situations.

The following is the discussion at that time, what I want to say is that company prove their service is trusted to user is important. This question is restate by myself.

> 想和大家讨论一个问题，假设我A公司提供了一个开源的Enclave代码，这个Enclave由我A公司签名然后部署在某些机器上，通过代码开源我希望大家相信我的Enclave绝对忠诚，这里面涉及了两个信任关系，第一个是由于Intel SGX的能力，A公司的Enclave跑在阿里云之类的远程计算节点上也是OK的，也就是说开发者是放心的，第二个信任关系是希望使用A公司提供的Enclave的用户能够信任这个Enclave，基于代码开源，用户能够放心的把秘密放到我A公司的Enclave上。但是此时，A公司的Enclave因为逻辑上的问题，需要seal（密封，可以理解为加密）秘密到文件系统上去，这里用到的seal key是CPU里的root seal key依据签名者信息MRSIGNER（前面说到这个Enclave是A公司签名的）派生出来的，那么A公司其实有能力另外写一个Enclave，同时还是由A公司签名，然后拿到相同的seal key，把之前那个seal file解密出来，那么这个可能是用户不放心的，这种矛盾，大家有什么想法吗

> 我自己的想法就是由用户保留这个密钥，seal之前Enclave问用户拿密钥，通过代码审计确保这个密钥不会离开Enclave被开发者知道，因为要考虑断电重启等因素，密钥一直停留在内存是不行的。简而言之就是开发者的Enclave用开发者无法知道的密钥来进行seal操作

**Comment by tonywu6** [comment]
> SecretPad run online

Do you mean the _SecretPad_ as distributed by _us_ (like the "all-in-one" archive currently downloadable through [our website][mvp]), unmodified at all?

Or do you mean a version of SecretPad that has been modified by a third party, and now _they_ would like to prove that their code is consistent with _our_ code?

[mvp]: https://secretflow-public.oss-cn-hangzhou.aliyuncs.com/mvp-packages/secretflow-allinone-package-latest.tar.gz

**Comment by LeoneChen** [comment]
I mean the SecretPad run by Ant (then give user online experience) can be different from open-sourced code, since there is no guarantee.

**Comment by tonywu6** [comment]
There is currently no way for an end user of the [online platform] to directly and fully verify that the software being used, as a whole, is a true representation of the published source code. In fact, that is most likely not the case. The platform could be using an old version of the software, or a modified version due to differences in infrastructure, etc. This is true for software offered as services in general.

[online platform]: https://www.secretflow.org.cn/docs/quickstart/pe6o3q

As a reminder, the online platform is being offered as a demonstration of what privacy-preserving computation workflows could look like, **not** as a fully-developed computing service. The same goes for the currently distributed "MVP" SecretPad, except the latter runs on your local machine. Neither are suitable for production use. A production-ready service will include many more security mechanisms, for example, [client-side encryption].

[client-side encryption]: https://docs.aws.amazon.com/clean-rooms/latest/userguide/crypto-computing.html

It's ultimately a matter of trust, yes. By using an online service, you are entrusting the service provider to abide by all security guarantees it makes, whether the provider is Ant or [Amazon] or [Azure].

[Amazon]: https://aws.amazon.com/clean-rooms/
[Azure]: https://learn.microsoft.com/en-us/azure/confidential-computing/multi-party-data

One of the goals of publishing SecretPad's source code is to enable other businesses to expand upon it and develop their own solutions. In turn, when they do so, their customers will have to trust them, and not just SecretFlow.

Open-sourcing does not automatically confer trust, but we hope it makes it easier for businesses to configure privacy-preserving systems, to satisfy regulatory requirements, and to allow third-party security audits, and therefore, build their own trust.

**Comment by LeoneChen** [comment]
Thanks for your answer~
